// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.2
// source: object_fetch.proto

package object_fetch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId     []byte `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ObjectLength int64  `protobuf:"varint,2,opt,name=object_length,json=objectLength,proto3" json:"object_length,omitempty"`
	RdmaSupport  bool   `protobuf:"varint,3,opt,name=rdma_support,json=rdmaSupport,proto3" json:"rdma_support,omitempty"`
	SpanCtx      []byte `protobuf:"bytes,4,opt,name=span_ctx,json=spanCtx,proto3" json:"span_ctx,omitempty"`
	ErrorMsg     string `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
}

func (x *FetchHeader) Reset() {
	*x = FetchHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_object_fetch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchHeader) ProtoMessage() {}

func (x *FetchHeader) ProtoReflect() protoreflect.Message {
	mi := &file_object_fetch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchHeader.ProtoReflect.Descriptor instead.
func (*FetchHeader) Descriptor() ([]byte, []int) {
	return file_object_fetch_proto_rawDescGZIP(), []int{0}
}

func (x *FetchHeader) GetObjectId() []byte {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

func (x *FetchHeader) GetObjectLength() int64 {
	if x != nil {
		return x.ObjectLength
	}
	return 0
}

func (x *FetchHeader) GetRdmaSupport() bool {
	if x != nil {
		return x.RdmaSupport
	}
	return false
}

func (x *FetchHeader) GetSpanCtx() []byte {
	if x != nil {
		return x.SpanCtx
	}
	return nil
}

func (x *FetchHeader) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ConnectionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info []byte `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_object_fetch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_object_fetch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_object_fetch_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionInfo) GetInfo() []byte {
	if x != nil {
		return x.Info
	}
	return nil
}

type RBuf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rbuf []byte `protobuf:"bytes,1,opt,name=rbuf,proto3" json:"rbuf,omitempty"`
}

func (x *RBuf) Reset() {
	*x = RBuf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_object_fetch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RBuf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBuf) ProtoMessage() {}

func (x *RBuf) ProtoReflect() protoreflect.Message {
	mi := &file_object_fetch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBuf.ProtoReflect.Descriptor instead.
func (*RBuf) Descriptor() ([]byte, []int) {
	return file_object_fetch_proto_rawDescGZIP(), []int{2}
}

func (x *RBuf) GetRbuf() []byte {
	if x != nil {
		return x.Rbuf
	}
	return nil
}

var File_object_fetch_proto protoreflect.FileDescriptor

var file_object_fetch_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x66, 0x65, 0x74, 0x63, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x64, 0x69, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x66, 0x65, 0x74, 0x63, 0x68, 0x22, 0xaa, 0x01, 0x0a, 0x0b,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x21, 0x0a,
	0x0c, 0x72, 0x64, 0x6d, 0x61, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x72, 0x64, 0x6d, 0x61, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x6e, 0x5f, 0x63, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x73, 0x70, 0x61, 0x6e, 0x43, 0x74, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x1a,
	0x0a, 0x04, 0x52, 0x42, 0x75, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x62, 0x75, 0x66, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x62, 0x75, 0x66, 0x42, 0x1a, 0x5a, 0x18, 0x64, 0x69,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x66, 0x65, 0x74, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_object_fetch_proto_rawDescOnce sync.Once
	file_object_fetch_proto_rawDescData = file_object_fetch_proto_rawDesc
)

func file_object_fetch_proto_rawDescGZIP() []byte {
	file_object_fetch_proto_rawDescOnce.Do(func() {
		file_object_fetch_proto_rawDescData = protoimpl.X.CompressGZIP(file_object_fetch_proto_rawDescData)
	})
	return file_object_fetch_proto_rawDescData
}

var file_object_fetch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_object_fetch_proto_goTypes = []interface{}{
	(*FetchHeader)(nil),    // 0: di_store.object_fetch.FetchHeader
	(*ConnectionInfo)(nil), // 1: di_store.object_fetch.ConnectionInfo
	(*RBuf)(nil),           // 2: di_store.object_fetch.RBuf
}
var file_object_fetch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_object_fetch_proto_init() }
func file_object_fetch_proto_init() {
	if File_object_fetch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_object_fetch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_object_fetch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_object_fetch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RBuf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_object_fetch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_object_fetch_proto_goTypes,
		DependencyIndexes: file_object_fetch_proto_depIdxs,
		MessageInfos:      file_object_fetch_proto_msgTypes,
	}.Build()
	File_object_fetch_proto = out.File
	file_object_fetch_proto_rawDesc = nil
	file_object_fetch_proto_goTypes = nil
	file_object_fetch_proto_depIdxs = nil
}
